### ISSUE TITLE
facilityuse_example_1.json doesn't pass validator due to SportsActivityLocation missing address,geo

### ISSUE THREAD

**Issue by lukehesluke** [openactive/data-models#22]
If you go to https://validator.openactive.io/?url=https%3A%2F%2Fwww.openactive.io%2Fdata-models%2Fversions%2F2.x%2Fexamples%2Ffacilityuse_example_1.json&version=2.0

You'll see that the errors in the side bar include the following:

```
Message
When publishing a SportsActivityLocation, a data publisher must provide at least one of address, geo.

While these properties are marked as recommended in the specification, a data publisher must provide as much detail in both address and geo for an event as possible.
```

I could submit a PR to add geo to the SportsActivityLocation items in that example if you like 😎

**Comment by nickevansuk** [comment]
Great spot @lukehesluke, this has now been resolved by https://github.com/openactive/data-models/commit/67596c9db2ec20e8ec37d3963d070baf96636e5a#diff-1770b2eaa6f2cf8f57e762ca7547fd46. This was indeed a bug.
